# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: grafana
      image: ghcr.io/general-intelligence-systems/grafana:12.1.1-debian-12-r1
    - name: grafana-operator
      image: ghcr.io/general-intelligence-systems/grafana-operator:5.19.4-debian-12-r2
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 5.19.4
dependencies:
- name: common
  repository: oci://ghcr.io/general-intelligence-systems/bitnami-charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Grafana Operator is a Kubernetes operator that enables the installation
  and management of Grafana instances, dashboards and plugins.
home: https://github.com/general-intelligence-systems/bitnami-charts
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/grafana/img/grafana-stack-220x234.png
keywords:
- grafana
- operator
- monitoring
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/general-intelligence-systems/bitnami-charts
name: grafana-operator
sources:
- https://github.com/general-intelligence-systems/bitnami-charts/tree/main/bitnami/grafana-operator
version: 4.10.0
